### ISSUE TITLE
Move this package into the ember-cli or emberjs GitHub org

### ISSUE THREAD

**Issue by steveszc** [ember-tooling/prettier-plugin-ember-template-tag#268]
This package is core infrastructure/tooling for Ember's GTS/GJS format. 
As such, it ought not be owned by an individual user, but rather it ought to be owned by one of the official Ember GitHub orgs such as [ember-cli ](https://github.com/ember-cli) or [emberjs](https://github.com/emberjs)

**Comment by simonihmig** [comment]
https://github.com/ember-tooling has been suggested as another org to host this from.

**Comment by gitKrystan** [comment]
Discussion here: https://discord.com/channels/480462759797063690/717767358743183412/1296905708763090975

**Comment by gitKrystan** [comment]
This is now part of the @ember-tooling org. Will work on figuring out NPM release stuff another day.
